services:
  backend:
    image: jadery/yall-rosher:be
    ports:
      - '8000:8000'
    container_name: backend
    restart: unless-stopped

  frontend:
    depends_on:
      - backend
    image: jadery/yall-rosher:fe
    ports:
      - '8080:8080'
    container_name: frontend
    restart: unless-stopped

  nginx:
    depends_on:
      - frontend
      - backend
    image: nginx:alpine
    volumes:
      # - ./certs:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    container_name: nginx
    restart: unless-stopped
