# Generated by Django 4.1 on 2024-02-26 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='shop.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='article',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
