# Generated by Django 4.2.10 on 2024-02-21 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Кошик', 'verbose_name_plural': 'Кошики'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterModelOptions(
            name='semicategory',
            options={'verbose_name': 'Підкатегорія', 'verbose_name_plural': 'Підкатегорії'},
        ),
        migrations.AlterModelOptions(
            name='typeclothes',
            options={'verbose_name': 'Тип одягу', 'verbose_name_plural': 'Типи одягу'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='category_type',
            new_name='semi_category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='semi_category',
            field=models.ManyToManyField(blank=True, null=True, to='shop.semicategory'),
        ),
    ]
