# Generated by Django 4.2.10 on 2024-05-19 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="variant_of_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="shop.variantofitem",
            ),
        ),
    ]
