# Generated by Django 4.1 on 2024-02-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_size_item_alter_item_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Червоний', 'Red'), ('Білий', 'White'), ('Зелений', 'Green'), ('Чорний', 'Black'), ('Сірий', 'Gray'), ('Жовтий', 'Yellow'), ('Фіолетовий', 'Pink'), ('Синій', 'Blue')], max_length=11)),
                ('hex', models.CharField(default='#ffffff', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='colors',
            field=models.ManyToManyField(to='shop.color'),
        ),
        migrations.AlterField(
            model_name='size',
            name='variant_of_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.color'),
        ),
        migrations.DeleteModel(
            name='VariantOfItem',
        ),
    ]
