# Generated by Django 4.1 on 2024-02-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_color_item_colors_alter_size_variant_of_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
