# Generated by Django 4.2.10 on 2024-02-22 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_category_type_semicategory_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='semi_category',
        ),
        migrations.AlterField(
            model_name='semicategory',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
