# Generated by Django 4.1 on 2024-02-26 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_color_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant_of_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XSS', 'Xss'), ('XS', 'Xs'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'Xl'), ('XLL', 'Xll'), ('XLLL', 'Xlll')], max_length=5)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.color')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='shop.item')),
            ],
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
