# Generated by Django 4.2.10 on 2024-02-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_category_semi_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XSS', 'Xss'), ('XS', 'Xs'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'Xl'), ('XLL', 'Xll'), ('XLLL', 'Xlll')], max_length=5)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='TypeClothes',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='semicategory',
            name='category',
            field=models.CharField(choices=[('Чоловіче', 'Clothes'), ('Жіноче', 'Shoes'), ('Аксесуари', 'Accessories')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semicategory',
            name='type',
            field=models.CharField(choices=[('Чоловіче', 'Men'), ('Жіноче', 'Women'), ('Унісекс', 'Unisex'), ('Дитяче', 'Child'), ('Дівчаче', 'Girl'), ('Хлопчаче', 'Boy')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ManyToManyField(to='shop.size'),
        ),
    ]
