# Generated by Django 4.2.10 on 2024-05-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_orderitem_alter_order_user_delete_cart_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(
                related_name="orders", through="shop.OrderItem", to="shop.variantofitem"
            ),
        ),
    ]
