# Generated by Django 4.1 on 2024-02-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_variant_of_item_delete_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variant_of_item',
            new_name='VariantOfItem',
        ),
    ]
