# Generated by Django 4.2.10 on 2024-05-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_order_items"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="semicategory",
            options={
                "ordering": ["type", "category", "name"],
                "verbose_name": "Підкатегорія",
                "verbose_name_plural": "Підкатегорії",
            },
        ),
        migrations.AddField(
            model_name="variantofitem",
            name="variant_of_item",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="variantofitem",
            name="size",
            field=models.CharField(
                choices=[
                    ("XXS", "Xss"),
                    ("XS", "Xs"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "Xl"),
                    ("XXL", "Xxl"),
                    ("XXXL", "Xxxl"),
                    ("36", "S36"),
                    ("37", "S37"),
                    ("38", "S38"),
                    ("39", "S39"),
                    ("40", "S40"),
                    ("41", "S41"),
                    ("42", "S42"),
                    ("43", "S43"),
                    ("44", "S44"),
                    ("45", "S45"),
                ],
                max_length=5,
            ),
        ),
    ]
