# Generated by Django 4.1 on 2024-02-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_variant_of_item_variantofitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='product',
            new_name='item',
        ),
    ]
