# Generated by Django 4.2.10 on 2024-06-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_semicategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
