# Generated by Django 4.1 on 2024-02-29 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_product_gallery_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('Чоловік', 'Male'), ('Жінка', 'Female'), ('Невідомо', 'Unknown'), ('Інша', 'Other')], default='Невідомо', max_length=20),
        ),
        migrations.AlterField(
            model_name='variantofitem',
            name='size',
            field=models.CharField(choices=[('XXS', 'Xss'), ('XS', 'Xs'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'Xl'), ('XXL', 'Xxl'), ('XXXL', 'Xxxl')], max_length=5),
        ),
    ]
