# Generated by Django 4.2.10 on 2024-06-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_order_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Очікує", "Pending"),
                    ("Обробляється", "Processing"),
                    ("Відправленно", "Shipped"),
                    ("Доставленно", "Delivered"),
                ],
                default="Очікує",
                max_length=20,
            ),
        ),
    ]
