# Generated by Django 4.2.10 on 2024-06-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_order_status_choiches"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ["name"],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товари",
            },
        ),
        migrations.AlterField(
            model_name="item",
            name="colors",
            field=models.ManyToManyField(blank=True, to="shop.color"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Очікує", "Pending"),
                    ("Обробляється", "Processing"),
                    ("Відправлено", "Shipped"),
                    ("Доставлено", "Delivered"),
                ],
                default="Очікує",
                max_length=20,
            ),
        ),
    ]
